production="yes"
sdl="yes"
sdl_path="../buildeps/sdl"
target="template_release"
ffmpeg_path="../buildeps/ffmpeg-master-latest-linux64-lgpl-godot"
use_breakpad="yes"
debug_symbols="yes"
separate_debug_symbols="yes"